### ISSUE TITLE
NPE inside query executor

### ISSUE THREAD

**Issue by jpbetz** [apache/incubator-pinot#30]
Just hit the below NPE, I believe it was triggered by this query:

```
SELECT COUNT(timestamp) FROM spans WHERE timestamp BETWEEN 1435708800 AND 1437519830 GROUP BY toServiceName
```

```
java.lang.NullPointerException
    at com.linkedin.pinot.core.operator.MCombineOperator.trimToSize(MCombineOperator.java:257)
    at com.linkedin.pinot.core.operator.MCombineOperator.nextBlock(MCombineOperator.java:246)
    at com.linkedin.pinot.core.operator.UResultOperator.nextBlock(UResultOperator.java:52)
    at com.linkedin.pinot.core.plan.GlobalPlanImplV0.execute(GlobalPlanImplV0.java:58)
    at com.linkedin.pinot.core.query.executor.ServerQueryExecutorV1Impl.processQuery(ServerQueryExecutorV1Impl.java:133)
    at com.linkedin.pinot.server.request.SimpleRequestHandler.processRequest(SimpleRequestHandler.java:81)
    at com.linkedin.pinot.transport.netty.NettyServer$NettyChannelInboundHandler.channelRead(NettyServer.java:218)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by kishoreg** [comment]
Is this real time only?.  Ping me on https://gitter.im/linkedin/pinot when
you get a chance

**Comment by jpbetz** [comment]
Yes, real time only.

**Comment by kishoreg** [comment]
Thanks Joe. Can you list the contents of index directory on each of the
servers. In one of your earlier messages, you mentioned there were few
crashes. Did you clean up index directory before restarting?

If you haven't specified the data dir during start up, it should be under
/tmp/pinotServerData.

thanks,
Kishore G

**Comment by jpbetz** [comment]
closing hopelessly stale issues I've opened
