### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by sunny209868** [apache/incubator-pinot#4467]
hi, Does anyone know how to solve server query error?
2019/07/24 10:58:18.989 ERROR [com.linkedin.pinot.core.operator.CombineOperator] [] Caught ExecutionException.
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.linkedin.pinot.core.operator.CombineOperator.getNextBlock(CombineOperator.java:164)
        at com.linkedin.pinot.core.operator.CombineOperator.getNextBlock(CombineOperator.java:42)
        at com.linkedin.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:35)
        at com.linkedin.pinot.core.operator.InstanceResponseOperator.getNextBlock(InstanceResponseOperator.java:34)
        at com.linkedin.pinot.core.operator.InstanceResponseOperator.getNextBlock(InstanceResponseOperator.java:23)
        at com.linkedin.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:35)
        at com.linkedin.pinot.core.plan.GlobalPlanImplV0.execute(GlobalPlanImplV0.java:45)
        at com.linkedin.pinot.core.query.executor.ServerQueryExecutorV1Impl.processQuery(ServerQueryExecutorV1Impl.java:159)
        at com.linkedin.pinot.core.query.scheduler.QueryScheduler.processQueryAndSerialize(QueryScheduler.java:127)
        at com.linkedin.pinot.core.query.scheduler.QueryScheduler.lambda$createQueryFutureTask$0(QueryScheduler.java:112)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.linkedin.pinot.core.util.trace.TraceContext.registerThreadToRequest(TraceContext.java:137)
        at com.linkedin.pinot.core.util.trace.TraceCallable.call(TraceCallable.java:37)
        ... 8 more

java.lang.RuntimeException: Caught exception while running CombinePlanNode.
        at com.linkedin.pinot.core.plan.CombinePlanNode.run(CombinePlanNode.java:117)
        at com.linkedin.pinot.core.plan.InstanceResponsePlanNode.run(InstanceResponsePlanNode.java:35)
        at com.linkedin.pinot.core.plan.GlobalPlanImplV0.execute(GlobalPlanImplV0.java:42)
        at com.linkedin.pinot.core.query.executor.ServerQueryExecutorV1Impl.processQuery(ServerQueryExecutorV1Impl.java:159)
        at com.linkedin.pinot.core.query.scheduler.QueryScheduler.processQueryAndSerialize(QueryScheduler.java:127)
        at com.linkedin.pinot.core.query.scheduler.QueryScheduler.lambda$createQueryFutureTask$0(QueryScheduler.java:112)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.linkedin.pinot.core.plan.CombinePlanNode.run(CombinePlanNode.java:107)
        ... 13 more
Caused by: java.lang.NullPointerException
        at com.linkedin.pinot.core.util.trace.TraceContext.registerThreadToRequest(TraceContext.java:137)
        at com.linkedin.pinot.core.util.trace.TraceCallable.call(TraceCallable.java:37)
        ... 8 more

server request response：

 QueryExecutionError:\njava.lang.RuntimeException: Caught exception while running CombinePlanNode.\n\tat com.linkedin.pinot.core.plan.CombinePlanNode.run(CombinePlanNode.java:117)\n\tat com.linkedin.pinot.core.plan.InstanceResponsePlanNode.run(InstanceResponsePlanNode.java:35)\n\tat com.linkedin.pinot.core.plan.GlobalPlanImplV0.execute(GlobalPlanImplV0.java:42)\n\tat com.linkedin.pinot.core.query.executor.ServerQueryExecutorV1Impl.processQuery(ServerQueryExecutorV1Impl.java:159)\n\tat com.linkedin.pinot.core.query.scheduler.QueryScheduler.processQueryAndSerialize(QueryScheduler.java:127)\n\tat com.linkedin.pinot.core.query.scheduler.QueryScheduler.lambda$createQueryFutureTask$0(QueryScheduler.java:112)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)\n\tat com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)\n\tat com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)

**Comment by xiangfu0** [comment]
Closing — this was a question or is no longer actionable.
