### ISSUE TITLE
Pinot ZK Session timeout

### ISSUE THREAD

**Issue by kishoreg** [apache/incubator-pinot#4974]
Scenario: Pinot disconnects from ZK (bcos of GC or network issue) which leads to session expiry (after 30 seconds timeout). Once the connection is reestablished, Helix invokes pre-connect callback but Pinot throws an exception in the callback since it thinks the server is already started.

```
2020/01/12 02:45:23.308 ERROR [ZkClient] [ZkClient-EventThread-203-localhost:2123] Error handling event ZkEvent[New session event sent to org.apache.helix.manager.zk.ZKHelixManager@1f939a0f]
java.lang.IllegalStateException: Server instance is already started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[guava-20.0.jar:?]
	at org.apache.pinot.server.starter.ServerInstance.start(ServerInstance.java:104) ~[classes/:?]
	at org.apache.helix.manager.zk.ParticipantManager.handleNewSession(ParticipantManager.java:110) ~[helix-core-0.8.4.jar:0.8.4]
	at org.apache.helix.manager.zk.ZKHelixManager.handleNewSessionAsParticipant(ZKHelixManager.java:1171) ~[helix-core-0.8.4.jar:0.8.4]
	at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:1131) ~[helix-core-0.8.4.jar:0.8.4]
	at org.apache.helix.manager.zk.zookeeper.ZkClient$5.run(ZkClient.java:840) ~[helix-core-0.8.4.jar:0.8.4]
	at org.apache.helix.manager.zk.zookeeper.ZkEventThread.run(ZkEventThread.java:69) ~[helix-core-0.8.4.jar:0.8.4]
```

**Comment by Jackie-Jiang** [comment]
@kishoreg Thanks for reporting the issue, and here is the fix: https://github.com/apache/incubator-pinot/pull/4976
