### ISSUE TITLE
java.lang.NoClassDefFoundError exception for Parquet file format ingestion

### ISSUE THREAD

**Issue by kishred** [apache/incubator-pinot#5387]
Got this error when ingest a parquet file.

```
Trying to create instance for class org.apache.pinot.plugin.ingestion.batch.standalone.SegmentGenerationJobRunner
Initializing PinotFS for scheme file, classname org.apache.pinot.spi.filesystem.LocalPinotFS
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/Path
	at org.apache.pinot.plugin.inputformat.parquet.ParquetRecordReader.init(ParquetRecordReader.java:48)
	at org.apache.pinot.plugin.ingestion.batch.common.SegmentGenerationTaskRunner.run(SegmentGenerationTaskRunner.java:88)
	at org.apache.pinot.plugin.ingestion.batch.standalone.SegmentGenerationJobRunner.run(SegmentGenerationJobRunner.java:190)
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.kickoffIngestionJob(IngestionJobLauncher.java:96)
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.runIngestionJob(IngestionJobLauncher.java:77)
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.main(IngestionJobLauncher.java:55)
	at org.apache.pinot.tools.admin.command.LaunchDataIngestionJobCommand.execute(LaunchDataIngestionJobCommand.java:50)
	at org.apache.pinot.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:156)
	at org.apache.pinot.tools.admin.PinotAdministrator.main(PinotAdministrator.java:168)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.Path
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 9 more (edited) 
```

@npawar provided following workaround to this issue which worked.

```
CLASSPATH_PREFIX="/Users/npawar/.m2/repository/org/apache/hadoop/hadoop-common/2.7.0/hadoop-common-2.7.0.jar:/Users/npawar/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar:/Users/npawar/.m2/repository/org/apache/hadoop/hadoop-auth/2.7.0/hadoop-auth-2.7.0.jar" bin/pinot-admin.sh LaunchDataIngestionJob  -jobSpecFile /Users/npawar/quick_start_configs/events-quick-start/segment-creation-job-parquet.yml
```

**Comment by fx19880617** [comment]
Thanks for putting this! Closed this issue.
