### ISSUE TITLE
java.lang.ClassCastException when running SQL queries

### ISSUE THREAD

**Issue by kishred** [apache/incubator-pinot#5448]
Getting java.lang.ClassCastException when running this SQL query:

`SELECT colA, colB, SUM(metricA) from table GROUP BY colA, colB`

`colA` and `colB` are STRING typed.

This SQL query works fine when blank column values in colB are discarded using WHERE clause.

`SELECT colA, colB, SUM(metricA) FROM table WHERE colB != '' GROUP BY colA, colB`

Note: Exact same query returns results on PQL interface.

Below is the exception stacktrace printed by pinotServer:

```
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at org.apache.pinot.core.operator.blocks.IntermediateResultsBlock.setDataTableColumn(IntermediateResultsBlock.java:290) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at org.apache.pinot.core.operator.blocks.IntermediateResultsBlock.getResultDataTable(IntermediateResultsBlock.java:264) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at org.apache.pinot.core.operator.blocks.IntermediateResultsBlock.getDataTable(IntermediateResultsBlock.java:229) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at org.apache.pinot.core.operator.blocks.InstanceResponseBlock.<init>(InstanceResponseBlock.java:43) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at org.apache.pinot.core.operator.InstanceResponseOperator.getNextBlock(InstanceResponseOperator.java:37) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at org.apache.pinot.core.operator.InstanceResponseOperator.getNextBlock(InstanceResponseOperator.java:26) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:49) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at org.apache.pinot.core.plan.GlobalPlanImplV0.execute(GlobalPlanImplV0.java:48) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at org.apache.pinot.core.query.executor.ServerQueryExecutorV1Impl.processQuery(ServerQueryExecutorV1Impl.java:220) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at org.apache.pinot.core.query.scheduler.QueryScheduler.processQueryAndSerialize(QueryScheduler.java:152) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at org.apache.pinot.core.query.scheduler.QueryScheduler.lambda$createQueryFutureTask$0(QueryScheduler.java:136) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at shaded.com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) [pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at shaded.com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) [pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at shaded.com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) [pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f840db6c84c69d2ebf137f1407332b517ce9322]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by npawar** [comment]
Thanks for reporting! This has been fixed in the linked PR
