### ISSUE TITLE
Show details of failure when schema upload fails

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#5463]
Noticed today that adding a schema with a field missing in a spec resulted in just 500 error with message "Failed to add schema". See below example, `timeType` is missing in the spec.
```
{
  "dimensionFieldSpecs": [{
    "name": "foo",
    "dataType": "STRING"
  }
  ],
  "timeFieldSpec": {
    "incomingGranularitySpec": {
      "dataType": "LONG",
      "name": "bar"
    }
  }
```
Response:
```
{
  "code": 500,
  "error": "Failed to add new schema test."
}
```
This message is not very helpful.
We need to walk through all possible invalid schema scenarios and handle them properly.

Tasks:
1) List and validate all cases 
2) Return proper message in case of validation failures
3) More test cases to catch these

**Comment by lgo** [comment]
+1! I was running into this while trying to upload a schema using `pinot-admin.sh AddSchema` and was just running into

```
Got Exception to upload Pinot Schema: a_schema
org.apache.pinot.common.exception.HttpErrorStatusException: Got error status code: 400 (Bad Request) with reason: "Cannot add invalid schema: a_schema" while sending request: http://10.100.26.49:9000/schemas to controller: <...>, version: Unknown
	at org.apache.pinot.common.utils.FileUploadDownloadClient.sendRequest(FileUploadDownloadClient.java:375) ~[pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-a8fbdaeffaf99c1df4258f60ecbbab1f553d7696]
	at org.apache.pinot.common.utils.FileUploadDownloadClient.addSchema(FileUploadDownloadClient.java:426) ~[pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-a8fbdaeffaf99c1df4258f60ecbbab1f553d7696]
	at org.apache.pinot.tools.admin.command.AddSchemaCommand.execute(AddSchemaCommand.java:120) [pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-a8fbdaeffaf99c1df4258f60ecbbab1f553d7696]
	at org.apache.pinot.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:156) [pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-a8fbdaeffaf99c1df4258f60ecbbab1f553d7696]
	at org.apache.pinot.tools.admin.PinotAdministrator.main(PinotAdministrator.java:168) [pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-a8fbdaeffaf99c1df4258f60ecbbab1f553d7696]
```

(which was a similar problem, the schema accidentally had a `STRING` in `dimensionFields`)

**Comment by npawar** [comment]
This should be fixed now
