### ISSUE TITLE
Exception using S3 as deep storage

### ISSUE THREAD

**Issue by pradeepgv42** [apache/incubator-pinot#5616]
I am seeing below exception trying to use S3 as deep storage. 
Seems like an issue with aws-sdk and httpclient version used. 

NoSuchMethodException was thrown when disabling normalizeUri. This indicates you are using an old version (< 4.5.8) of Apache http client. It is recommended to use http client version >= 4.5.9 to avoid the breaking change introduced in apache client 4.5.7 and the latency in exception handling. See https://github.com/aws/aws-sdk-java/issues/1919 for more information
Exception in thread "main" java.lang.BootstrapMethodError: call site initialization exception
        at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
        at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
        at software.amazon.awssdk.http.apache.ApacheHttpClient.transformHeaders(ApacheHttpClient.java:268)
        at software.amazon.awssdk.http.apache.ApacheHttpClient.createResponse(ApacheHttpClient.java:253)
        at software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:233)
        at software.amazon.awssdk.http.apache.ApacheHttpClient.access$500(ApacheHttpClient.java:98)
        at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:213)

Changing the top-level pom.xml seems to work

       <dependency>
         <groupId>org.apache.httpcomponents</groupId>
         <artifactId>httpclient</artifactId>
-        <version>4.5.3</version>
+        <version>4.5.9</version>
       </dependency>
       <dependency>
         <groupId>org.apache.httpcomponents</groupId>
         <artifactId>httpcore</artifactId>
-        <version>4.4.6</version>
+        <version>4.4.9</version>
       </dependency>

**Comment by kishoreg** [comment]
@KKcorps can you please take this up.

**Comment by KKcorps** [comment]
Sure. Should I remove parent from this module and then shade the dependency as per our discussion?

**Comment by kishoreg** [comment]
or shade this jar explicitly and use the version we need.

**Comment by pradeepgv42** [comment]
this was fixed in https://github.com/apache/incubator-pinot/pull/5670
