### ISSUE TITLE
Requesting support for DISTINCTCOUNT on BYTES typed columns

### ISSUE THREAD

**Issue by tmwangi** [apache/incubator-pinot#5690]
Currently DISTINCTCOUNT on a column with the BYTES type does not work.  Our usage of BYTES columns is to represent fields that were originally in bytes form and were ByteBuffer before being serialized into a Pinot column. Would you suggest to convert these to a hex-encoded string? The error returned is:

```
org.apache.pinot.client.PinotClientException: Query had processing exceptions: [{"errorCode":200,"message":"QueryExecutionError:
java.lang.IllegalStateException: Illegal data type for DISTINCT_COUNT aggregation function: BYTES
  at org.apache.pinot.core.query.aggregation.function.DistinctCountAggregationFunction.aggregate(DistinctCountAggregationFunction.java:91)
  at org.apache.pinot.core.query.aggregation.DefaultAggregationExecutor.aggregate(DefaultAggregationExecutor.java:94)
  at org.apache.pinot.core.operator.query.AggregationOperator.getNextBlock(AggregationOperator.java:65)
  at org.apache.pinot.core.operator.query.AggregationOperator.getNextBlock(AggregationOperator.java:35)
  at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:49)
  at
```

**Comment by buchireddy** [comment]
cc @kishoreg

**Comment by Jackie-Jiang** [comment]
It's very straight forward to add BYTES support for DISTINCTCOUNT. Will submit a PR soon.

**Comment by tmwangi** [comment]
Cool. Thanks @Jackie-Jiang

**Comment by Jackie-Jiang** [comment]
#5701

**Comment by tmwangi** [comment]
Thanks @Jackie-Jiang
