### ISSUE TITLE
Requesting GROUP BY support on BYTES typed columns

### ISSUE THREAD

**Issue by tmwangi** [apache/incubator-pinot#5691]
Currently Group By on a BYTES typed column does not work. Our usage of BYTES columns is to represent fields that were originally in bytes form and were ByteBuffer before being serialized into a Pinot column. Would you suggest to convert these to a hex-encoded string? The error I get is:

```
org.apache.pinot.client.PinotClientException: Query had processing exceptions: 
[{"errorCode":200,"message":"QueryExecutionError:
java.lang.IllegalArgumentException: Illegal data type for no-dictionary key generator: BYTES
  at org.apache.pinot.core.query.aggregation.groupby.NoDictionarySingleColumnGroupKeyGenerator.createGroupKeyMap(NoDictionarySingleColumnGroupKeyGenerator.java:149)
  at org.apache.pinot.core.query.aggregation.groupby.NoDictionarySingleColumnGroupKeyGenerator.<init>(NoDictionarySingleColumnGroupKeyGenerator.java:58)
  at org.apache.pinot.core.query.aggregation.groupby.DefaultGroupByExecutor.<init>(DefaultGroupByExecutor.java:102)
  at org.apache.pinot.core.operator.query.AggregationGroupByOrderByOperator.getNextBlock(AggregationGroupByOrderByOperator.java:101)
  at org.apache.pinot.core.operator.query.AggregationGroupByOrderByOperator.getNextBlock(AggregationGroupByOrderByOperator.java:38)
  at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:49)
  at org.apache.pinot.core.operator.CombineGroupByOrderByOperator$1.runJob(CombineGroupByOrderByOperator.java:134)
  at org.apache.pinot.core.util.trace.TraceRunnable.run(TraceRunnable.java:40)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at
```

**Comment by fx19880617** [comment]
I think this is due to No Implementation for key generation of non-dictionary bytes column. I feel we can somehow use hex encoding/decoding for this?
@Jackie-Jiang @npawar @siddharthteotia @mayankshriv

**Comment by Jackie-Jiang** [comment]
Should be straight forward. Will take a look soon.

**Comment by tmwangi** [comment]
Cool. Thanks @Jackie-Jiang

**Comment by Jackie-Jiang** [comment]
#5708

**Comment by buchi-busireddy** [comment]
FYI, seeing these exceptions in the latest `0.5.0` pinot release when trying to group by multiple columns which also includes `BYTES` columns.

```java
2020-10-22 19:48:20.591 [grpc-default-executor-779] ERROR o.h.c.q.s.p.PinotBasedRequestHandler - An error occurred while executing: Select dateTimeConvert(start_time_millis,?,?,?), trace_id, COUNT(*) FROM spanEventView WHERE customer_id = ? AND ( ( start_time_millis >= ? AND start_time_millis < ? ) AND ( api_boundary_type = ? AND api_id != ? AND ( trace_id IN (?, ?, ?, ?, ?) ) ) ) GROUP BY dateTimeConvert(start_time_millis,?,?,?), trace_id limit 50000org.apache.pinot.client.PinotClientException: Query had processing exceptions:[{"message":"QueryExecutionError:\norg.apache.pinot.core.query.exception.BadQueryRequestException: java.lang.IllegalArgumentException: Value: {\"bytes\":\"Caw9KXf+zBjdF1rFAXsSuA==\"} is not Hex encoded
at org.apache.pinot.core.operator.filter.predicate.PredicateEvaluatorProvider.getPredicateEvaluator(PredicateEvaluatorProvider.java:84)
at org.apache.pinot.core.plan.FilterPlanNode.constructPhysicalOperator(FilterPlanNode.java:130)
at org.apache.pinot.core.plan.FilterPlanNode.constructPhysicalOperator(FilterPlanNode.java:77)
at org.apache.pinot.core.plan.FilterPlanNode.run(FilterPlanNode.java:61)
at org.apache.pinot.core.plan.DocIdSetPlanNode.run(DocIdSetPlanNode.java:41)
at org.apache.pinot.core.plan.ProjectionPlanNode.run(ProjectionPlanNode.java:52)
at org.apache.pinot.core.plan.TransformPlanNode.run(TransformPlanNode.java:52)
at org.apache.pinot.core.plan.AggregationGroupByOrderByPlanNode.run(AggregationGroupByOrderByPlanNode.java:107)
at org.apache.pinot.core.plan.AggregationGroupByOrderByPlanNode.run(AggregationGroupByOrderByPlanNode.java:40)
at org.apache.pinot.core.plan.CombinePlanNode.run(CombinePlanNode.java:89)
at org.apache.pinot.core.plan.InstanceResponsePlanNode.run(InstanceResponsePlanNode.java:33)
at org.apache.pinot.core.plan.GlobalPlanImplV0.execute(GlobalPlanImplV0.java:45)
at org.apache.pinot.core.query.executor.ServerQueryExecutorV1Impl.processQuery(ServerQueryExecutorV1Impl.java:221)
at org.apache.pinot.core.query.scheduler.QueryScheduler.processQueryAndSerialize(QueryScheduler.java:155)","errorCode":200},{"message":"QueryExecutionError:\norg.apache.pinot.core.query.exception.BadQueryRequestException: java.lang.IllegalArgumentException: Value: {\"bytes\":\"Caw9KXf+zBjdF1rFAXsSuA==\"} is not Hex encoded
at org.apache.pinot.core.operator.filter.predicate.PredicateEvaluatorProvider.getPredicateEvaluator(PredicateEvaluatorProvider.java:84)
at org.apache.pinot.core.plan.FilterPlanNode.constructPhysicalOperator(FilterPlanNode.java:130)
at org.apache.pinot.core.plan.FilterPlanNode.constructPhysicalOperator(FilterPlanNode.java:77)
at org.apache.pinot.core.plan.FilterPlanNode.run(FilterPlanNode.java:61)
at org.apache.pinot.core.plan.DocIdSetPlanNode.run(DocIdSetPlanNode.java:41)
at org.apache.pinot.core.plan.ProjectionPlanNode.run(ProjectionPlanNode.java:52)
at org.apache.pinot.core.plan.TransformPlanNode.run(TransformPlanNode.java:52)
at org.apache.pinot.core.plan.AggregationGroupByOrderByPlanNode.run(AggregationGroupByOrderByPlanNode.java:107)
at org.apache.pinot.core.plan.AggregationGroupByOrderByPlanNode.run(AggregationGroupByOrderByPlanNode.java:40)
at org.apache.pinot.core.plan.CombinePlanNode.run(CombinePlanNode.java:89)
at org.apache.pinot.core.plan.InstanceResponsePlanNode.run(InstanceResponsePlanNode.java:33)
at org.apache.pinot.core.plan.GlobalPlanImplV0.execute(GlobalPlanImplV0.java:45)
at org.apache.pinot.core.query.executor.ServerQueryExecutorV1Impl.processQuery(ServerQueryExecutorV1Impl.java:221)
at org.apache.pinot.core.query.scheduler.QueryScheduler.processQueryAndSerialize(QueryScheduler.java:155)","errorCode":200},{"message":"QueryExecutionError:\norg.apache.pinot.core.query.exception.BadQueryRequestException: java.lang.IllegalArgumentException: Value: {\"bytes\":\"Caw9KXf+zBjdF1rFAXsSuA==\"} is not Hex encoded
at org.apache.pinot.core.operator.filter.predicate.PredicateEvaluatorProvider.getPredicateEvaluator(PredicateEvaluatorProvider.java:84)
at org.apache.pinot.core.plan.FilterPlanNode.constructPhysicalOperator(FilterPlanNode.java:130)
at org.apache.pinot.core.plan.FilterPlanNode.constructPhysicalOperator(FilterPlanNode.java:77)
at org.apache.pinot.core.plan.FilterPlanNode.run(FilterPlanNode.java:61)
at org.apache.pinot.core.plan.DocIdSetPlanNode.run(DocIdSetPlanNode.java:41)
at org.apache.pinot.core.plan.ProjectionPlanNode.run(ProjectionPlanNode.java:52)
at org.apache.pinot.core.plan.TransformPlanNode.run(TransformPlanNode.java:52)
at org.apache.pinot.core.plan.AggregationGroupByOrderByPlanNode.run(AggregationGroupByOrderByPlanNode.java:107)
at org.apache.pinot.core.plan.AggregationGroupByOrderByPlanNode.run(AggregationGroupByOrderByPlanNode.java:40)
at org.apache.pinot.core.plan.CombinePlanNode.run(CombinePlanNode.java:89)
at org.apache.pinot.core.plan.InstanceResponsePlanNode.run(InstanceResponsePlanNode.java:33)
at org.apache.pinot.core.plan.GlobalPlanImplV0.execute(GlobalPlanImplV0.java:45)
at org.apache.pinot.core.query.executor.ServerQueryExecutorV1Impl.processQuery(ServerQueryExecutorV1Impl.java:221)
at org.apache.pinot.core.query.scheduler.QueryScheduler.processQueryAndSerialize(QueryScheduler.java:155)","errorCode":200}]
```
cc @Jackie-Jiang
