### ISSUE TITLE
Unable to run PerfBenchmarkRunner

### ISSUE THREAD

**Issue by mayankshriv** [apache/incubator-pinot#5790]
It seems that PerfBenchmarkRunner gives the following error when started. This is likely due to conflicting version of grizzly http server getting pulled in from different transitive dependencies. I noticed that if I delete the `tyrus-standalone-jar` from IDE, then I am able to run PerfBenchmarkRunner.

The only class that uses `tyrus` seems to be MeetupRvspStream.

To reproduce, run PerfBenchmarkRunner from IDE with arguments `-mode startAllButServer`.

```
Exception in thread "main" java.lang.NoSuchMethodError: org.glassfish.grizzly.http.server.ServerConfiguration.addHttpHandler(Lorg/glassfish/grizzly/http/server/HttpHandler;[Lorg/glassfish/grizzly/http/server/HttpHandlerRegistration;)V
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:258)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:114)
	at org.apache.pinot.controller.api.ControllerAdminApiApplication.start(ControllerAdminApiApplication.java:112)
	at org.apache.pinot.controller.ControllerStarter.setUpPinotController(ControllerStarter.java:419)
	at org.apache.pinot.controller.ControllerStarter.start(ControllerStarter.java:290)
	at org.apache.pinot.tools.perf.PerfBenchmarkDriver.startController(PerfBenchmarkDriver.java:202)
	at org.apache.pinot.tools.perf.PerfBenchmarkDriver.run(PerfBenchmarkDriver.java:175)
	at org.apache.pinot.tools.perf.PerfBenchmarkRunner.startAllButServer(PerfBenchmarkRunner.java:110)
	at org.apache.pinot.tools.perf.PerfBenchmarkRunner.execute(PerfBenchmarkRunner.java:96)
	at org.apache.pinot.tools.perf.PerfBenchmarkRunner.main(PerfBenchmarkRunner.java:188)
```

**Comment by xiangfu0** [comment]
Closing — this has been fixed in PR #5417 (fix server pre-load issue) and PR #9298 (fix PerfBenchmarkRunner to skip the tmp dir), plus multiple additional fixes.
