### ISSUE TITLE
String date format - not working on data ingestion

### ISSUE THREAD

**Issue by itzikiusa** [apache/incubator-pinot#5845]
Hi,
trying to ingest data with timestamp in a format of: 'yyyy-MM-dd HH:mm:ss'
scheme:
```
{
  "schemaName": "transcript",
  "dimensionFieldSpecs": [
    {
      "name": "casino_id",
      "dataType": "INT"
    },
    {
      "name": "round_id",
      "dataType": "STRING"
    },
    {
      "name": "trans_id",
      "dataType": "STRING"
    },
    {
      "name": "provider_id",
      "dataType": "INT"
    },
    {
      "name": "game_id",
      "dataType": "STRING"
    }
  ],
  "metricFieldSpecs": [
    {
      "name": "amount",
      "dataType": "FLOAT"
    },
    {
      "name": "bonus_money",
      "dataType": "FLOAT"
    },
    {
      "name": "real_money",
      "dataType": "FLOAT"
    }
  ],
  "dateTimeFieldSpecs": [{
    "name": "timestamp",
    "dataType": "STRING",
    "format" : "1:SECONDS:SIMPLE_DATE_FORMAT:yyyy-MM-dd HH:mm:ss",
    "granularity": "1:DAYS"
  }]
}


and getting this error:
Got exception to kick off standalone data ingestion job - 
java.lang.RuntimeException: Caught exception during running - org.apache.pinot.plugin.ingestion.batch.standalone.SegmentGenerationJobRunner
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.kickoffIngestionJob(IngestionJobLauncher.java:137) ~[pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.runIngestionJob(IngestionJobLauncher.java:110) ~[pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.tools.admin.command.LaunchDataIngestionJobCommand.execute(LaunchDataIngestionJobCommand.java:123) [pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:150) [pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.tools.admin.PinotAdministrator.main(PinotAdministrator.java:162) [pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
Caused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 10: transcript_OFFLINE_2020-08-08 03:01:30_2020-08-08 03:01:30_0.tar.gz
	at java.net.URI.create(URI.java:852) ~[?:1.8.0_252]
	at java.net.URI.resolve(URI.java:1036) ~[?:1.8.0_252]
	at org.apache.pinot.plugin.ingestion.batch.standalone.SegmentGenerationJobRunner.run(SegmentGenerationJobRunner.java:204) ~[pinot-batch-ingestion-standalone-0.5.0-SNAPSHOT-shaded.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.kickoffIngestionJob(IngestionJobLauncher.java:135) ~[pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	... 4 more
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 10: transcript_OFFLINE_2020-08-08 03:01:30_2020-08-08 03:01:30_0.tar.gz
	at java.net.URI$Parser.fail(URI.java:2848) ~[?:1.8.0_252]
	at java.net.URI$Parser.checkChars(URI.java:3021) ~[?:1.8.0_252]
	at java.net.URI$Parser.parse(URI.java:3048) ~[?:1.8.0_252]
	at java.net.URI.<init>(URI.java:588) ~[?:1.8.0_252]
	at java.net.URI.create(URI.java:850) ~[?:1.8.0_252]
	at java.net.URI.resolve(URI.java:1036) ~[?:1.8.0_252]
	at org.apache.pinot.plugin.ingestion.batch.standalone.SegmentGenerationJobRunner.run(SegmentGenerationJobRunner.java:204) ~[pinot-batch-ingestion-standalone-0.5.0-SNAPSHOT-shaded.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.kickoffIngestionJob(IngestionJobLauncher.java:135) ~[pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	... 4 more
Exception caught: 
java.lang.RuntimeException: Caught exception during running - org.apache.pinot.plugin.ingestion.batch.standalone.SegmentGenerationJobRunner
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.kickoffIngestionJob(IngestionJobLauncher.java:137) ~[pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.runIngestionJob(IngestionJobLauncher.java:110) ~[pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.tools.admin.command.LaunchDataIngestionJobCommand.execute(LaunchDataIngestionJobCommand.java:123) ~[pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:150) [pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.tools.admin.PinotAdministrator.main(PinotAdministrator.java:162) [pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
Caused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 10: transcript_OFFLINE_2020-08-08 03:01:30_2020-08-08 03:01:30_0.tar.gz
	at java.net.URI.create(URI.java:852) ~[?:1.8.0_252]
	at java.net.URI.resolve(URI.java:1036) ~[?:1.8.0_252]
	at org.apache.pinot.plugin.ingestion.batch.standalone.SegmentGenerationJobRunner.run(SegmentGenerationJobRunner.java:204) ~[pinot-batch-ingestion-standalone-0.5.0-SNAPSHOT-shaded.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	at org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher.kickoffIngestionJob(IngestionJobLauncher.java:135) ~[pinot-all-0.5.0-SNAPSHOT-jar-with-dependencies.jar:0.5.0-SNAPSHOT-d8264c144f9655ebfa90059b5c9f74a007363f54]
	... 4 more
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 10: transcript_OFFLINE_2020-08-08 03:01:30_2020-08-08 03:01:30_0.tar.gz
	at java.net.URI$Parser.fail(URI.java:2848) ~[?:1.8.0_252]
	at java.net.URI$Parser.checkChars(URI.java:3021) ~[?:1.8.0_252]
	at java.net.URI$Parser.parse(URI.java:3048) ~[?:1.8.0_252]
	at java.net.URI.<init>(URI.java:588) ~[?:1.8.0_252]
	at java.net.URI.create(URI.java:850) ~[?:1.8.0_252]
	at java.net.URI.resolve(URI.java:1036) ~[?:1.8.0_252]



when changing data and reading an epochtime, all works perfectly

**Comment by itzikiusa** [comment]
thanks @KKcorps 
can use the following config to solve the issue:

```
segmentNameGeneratorSpec:
  type: normalizedDate
  configs:
    segment.name.prefix: 'airlineStats_batch'
    exclude.sequence.id: true`

**Comment by KKcorps** [comment]
For future reference, add the following to the job spec
```yaml
segmentNameGeneratorSpec:
    type: normalizedDate
```
