### ISSUE TITLE
Standalone ingestion using SegmentUriPush to S3 does not work

### ISSUE THREAD

**Issue by lgo** [apache/incubator-pinot#5877]
Here's some of the setup:
```
# pinot controller properties.

# Requires `-Dplugins.dir=/opt/pinot/plugins -Dplugins.include=pinot-s3`
#
pinot.controller.storage.factory.class.s3=org.apache.pinot.plugin.filesystem.S3PinotFS
# Any S3 region
pinot.controller.storage.factory.s3.region=us-west-1
# Data directory for Pinot.
controller.data.dir=s3://mybucket/myfolder/pinot
```

When using an ingestion spec like the following
```yaml
executionFrameworkSpec:
    name: 'standalone'
    segmentGenerationJobRunnerClassName: 'org.apache.pinot.plugin.ingestion.batch.standalone.SegmentGenerationJobRunner'
    segmentTarPushJobRunnerClassName: 'org.apache.pinot.plugin.ingestion.batch.standalone.SegmentTarPushJobRunner'
    segmentUriPushJobRunnerClassName: 'org.apache.pinot.plugin.ingestion.batch.standalone.SegmentUriPushJobRunner'
jobType: SegmentCreationAndUriPush
inputDirURI: ...
outputDirURI: 's3://mybucket/myfolder/pinot'
overwriteOutput: true
pinotFSSpecs:
    - scheme: s3
      className: org.apache.pinot.plugin.filesystem.S3PinotFS
      configs:
        region: 'us-west-2'
pushJobSpec:
    # NB: This is particularly weird. Specifically, this seems
    # to be the "adjusted path" that is provided to the controller. I assume
    # that is because the ingestion job URI may not be the same for a
    # Controller?
    segmentUriPrefix: 's3://'
    segmentUriSuffix: ''
recordReaderSpec:
    # Dataset specific config.
tableSpec:
    # Table specific config.
pinotClusterSpecs:
    # Cluster specific config.
```

When using the standalone ingestion job via `bin/pinot-ingestion-job.sh`
* Segment generation is fine.
* Data shows up on S3 as expected and the logline in `S3PinotFS` for `Copy` has the correct path, but the `SegmentPushUtils` does not, and the the `SegmentUriPushJobRunner` fails will get a 500 from the controller due to the path not being found.

```
2020/08/17 14:45:38.719 INFO [S3PinotFS] [main] Copy /tmp/pinot-a4064eea-301d-4f24-8861-0575a73e6a0b/output/mytable_OFFLINE_1569293930_1569293987_0.tar.gz from local to s3://mybucket/myfolder/pinot/mytable_OFFLINE_1569293930_1569293987_0.tar.gz
2020/08/17 14:45:38.794 INFO [IngestionJobLauncher] [main] Trying to create instance for class org.apache.pinot.plugin.ingestion.batch.standalone.SegmentUriPushJobRunner
2020/08/17 14:45:38.795 INFO [PinotFSFactory] [main] Initializing PinotFS for scheme s3, classname org.apache.pinot.plugin.filesystem.S3PinotFS
2020/08/17 14:45:38.920 INFO [SegmentPushUtils] [main] Start sending table mytable segment URIs: [s3:///myfolder/pinot/mytable_OFFLINE_1569293930_1569293987_0.tar.gz] to locations: [org.apache.pinot.spi.ingestion.batch.spec.PinotClusterSpec@4e07b95f]
2020/08/17 14:45:38.920 INFO [SegmentPushUtils] [main] Sending table mytable segment URI: s3:///myfolder/pinot/mytable_OFFLINE_1569293930_1569293987_0.tar.gz to location
```

I suspect it's related to how the output path is constructed here before `SegmentPushUtils.sendSegmentUris` but I have not confirmed it.

https://github.com/apache/incubator-pinot/blob/2b58bfb520df074f691277f2ae5b01ecb5c686c2/pinot-plugins/pinot-batch-ingestion/pinot-batch-ingestion-standalone/src/main/java/org/apache/pinot/plugin/ingestion/batch/standalone/SegmentUriPushJobRunner.java#L90-L91

It also was not clear that the same issue would happen with the Hadoop/Spark SegmentUri push jobs.

**Comment by lgo** [comment]
Also, this is using a build that includes #5836 which I initially thought would address the error. The issue could also be that the implementation of `listFiles` is failing to include the bucket.

**Comment by kishoreg** [comment]
I thought this was fixed. cc @KKcorps

**Comment by lgo** [comment]
This is slightly different, in that the PR (#5836) was fixing ingestion _from_ S3 not publishing _to_ S3.

**Comment by kishoreg** [comment]
anything in controller logs?

**Comment by lgo** [comment]
Yep, the controller logs look similar.

```
2020/08/17 14:45:38.927 INFO [PinotSegmentUploadDownloadRestletResource] [jersey-server-managed-async-executor-1] HTTP Header: UPLOAD_TYPE is: URI
2020/08/17 14:45:38.927 INFO [PinotSegmentUploadDownloadRestletResource] [jersey-server-managed-async-executor-1] HTTP Header: DOWNLOAD_URI is: s3:///myfolder/pinot/mytable_OFFLINE_1569293930_1569293987_0.tar.gz
2020/08/17 14:45:38.927 INFO [PinotSegmentUploadDownloadRestletResource] [jersey-server-managed-async-executor-1] Downloading segment from s3:///myfolder/pinot/mytable_OFFLINE_1569293930_1569293987_0.tar.gz to /pay/pinot/data/fileUploadTemp/tmp-3aa3e730-d2f0-4445-bc1e-24ad59a84c56 for table null
2020/08/17 14:45:38.927 INFO [S3PinotFS] [jersey-server-managed-async-executor-1] Copy s3:///myfolder/pinot/mytable_OFFLINE_1569293930_1569293987_0.tar.gz to local /pay/pinot/data/fileUploadTemp/tmp-3aa3e730-d2f0-4445-bc1e-24ad59a84c56
2020/08/17 14:45:38.927 WARN [PinotFSSegmentFetcher] [jersey-server-managed-async-executor-1] Caught exception while fetching segment from: s3:///myfolder/pinot/mytable_OFFLINE_1569293930_1569293987_0.tar.gz to: /pay/pinot/data/fileUploadTemp/tmp-3aa3e730-d2f0-4445-bc1e-24ad59a84c56
java.io.IOException: java.net.URISyntaxException: Expected scheme-specific part at index 3: s3:
	at org.apache.pinot.plugin.filesystem.S3PinotFS.getBase(S3PinotFS.java:156) ~[pinot-s3-0.5.0-2020-08-13-SNAPSHOT-shaded.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.apache.pinot.plugin.filesystem.S3PinotFS.copyToLocalFile(S3PinotFS.java:413) ~[pinot-s3-0.5.0-2020-08-13-SNAPSHOT-shaded.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.apache.pinot.common.utils.fetcher.PinotFSSegmentFetcher.fetchSegmentToLocalWithoutRetry(PinotFSSegmentFetcher.java:31) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.apache.pinot.common.utils.fetcher.BaseSegmentFetcher.lambda$fetchSegmentToLocal$0(BaseSegmentFetcher.java:71) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.apache.pinot.spi.utils.retry.BaseRetryPolicy.attempt(BaseRetryPolicy.java:50) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.apache.pinot.common.utils.fetcher.BaseSegmentFetcher.fetchSegmentToLocal(BaseSegmentFetcher.java:69) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.apache.pinot.common.utils.fetcher.SegmentFetcherFactory.fetchSegmentToLocal(SegmentFetcherFactory.java:110) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.apache.pinot.common.utils.fetcher.SegmentFetcherFactory.fetchSegmentToLocal(SegmentFetcherFactory.java:118) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.apache.pinot.controller.api.resources.PinotSegmentUploadDownloadRestletResource.downloadSegmentFileFromURI(PinotSegmentUploadDownloadRestletResource.java:358) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.apache.pinot.controller.api.resources.PinotSegmentUploadDownloadRestletResource.uploadSegment(PinotSegmentUploadDownloadRestletResource.java:213) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.apache.pinot.controller.api.resources.PinotSegmentUploadDownloadRestletResource.uploadSegmentAsJsonV2(PinotSegmentUploadDownloadRestletResource.java:438) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.lambda$apply$0(ResourceMethodInvoker.java:381) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$2$1.run(ServerRuntime.java:819) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$2.run(ServerRuntime.java:814) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 3: s3:
	at java.net.URI$Parser.fail(URI.java:2848) ~[?:1.8.0_265]
	at java.net.URI$Parser.failExpecting(URI.java:2854) ~[?:1.8.0_265]
	at java.net.URI$Parser.parse(URI.java:3057) ~[?:1.8.0_265]
	at java.net.URI.<init>(URI.java:673) ~[?:1.8.0_265]
	at java.net.URI.<init>(URI.java:774) ~[?:1.8.0_265]
	at org.apache.pinot.plugin.filesystem.S3PinotFS.getBase(S3PinotFS.java:154) ~[pinot-s3-0.5.0-2020-08-13-SNAPSHOT-shaded.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
	... 34 more
```

**Comment by KKcorps** [comment]
Looking into it @lgo

**Comment by KKcorps** [comment]
Hi @lgo, Can you set `segmentUriPrefix` to `s3:/` and try. That seems to work on my end.

**Comment by lgo** [comment]
Saw your earlier comment re `segmentUriPrefix`. I just got it to work with the configuration:
```
segmentUriPrefix: 's3://mybucket'
```

But your PR for removing the need for these and the complexity of configuring S3 is fantastic!

**Comment by fx19880617** [comment]
I've updated the ingestion uri push job in: https://github.com/apache/incubator-pinot/pull/5897

So users don't need to set `segmentUriPrefix` for push jobs

**Comment by kishoreg** [comment]
@fx19880617 can we close this

**Comment by fx19880617** [comment]
Here is also a doc for using s3 as deep store: https://docs.pinot.apache.org/users/tutorials/use-s3-as-deep-store-for-pinot
