### ISSUE TITLE
Failure to build in-memory segments after turning on consumingSegment reload

### ISSUE THREAD

**Issue by chenboat** [apache/incubator-pinot#6174]
When we are evaluating the schema update improvement ([PR4954](https://github.com/apache/incubator-pinot/pull/4954)), we found segment build error during sealing of the consuming segment after we add new columns to the schema. This in turn stopped the realtime ingestion entirely. 

Error stack:
```
java.lang.ClassCastException: org.apache.pinot.core.segment.index.readers.ConstantValueDoubleDictionary cannot be cast to org.apache.pinot.core.realtime.impl.dictionary.BaseMutableDictionary
	at o.a.p.c.r.c.s.RealtimeColumnStatistics.<init>(RealtimeColumnStatistics.java:46)
	at o.a.p.c.r.c.s.RealtimeSegmentStatsContainer.<init>(RealtimeSegmentStatsContainer.java:46)
	at o.a.p.c.r.c.s.RealtimeSegmentSegmentCreationDataSource.gatherStats(RealtimeSegmentSegmentCreationDataSource.java:51)
	at o.a.p.c.s.c.i.SegmentIndexCreationDriverImpl.init(SegmentIndexCreationDriverImpl.java:141)
	at o.a.p.c.r.c.RealtimeSegmentConverter.build(RealtimeSegmentConverter.java:140)
	at o.a.p.c.d.m.r.LLRealtimeSegmentDataManager.buildSegmentInternal(LLRealtimeSegmentDataManager.java:720)
	at o.a.p.c.d.m.r.LLRealtimeSegmentDataManager.buildSegmentForCommit(LLRealtimeSegmentDataManager.java:671)
	at o.a.p.c.d.m.r.LLRealtimeSegmentDataManager$PartitionConsumer.run(LLRealtimeSegmentDataManager.java:588)
	at jav...
```

To reproduce this issue, turn on
`  pinot.server.instance.reload.consumingSegment=true
`
and add a new column to the table schema. Then wait for the next segment flush.

@Jackie-Jiang @mcvsubbu @haibow @yupeng9 @npawar

**Comment by Jackie-Jiang** [comment]
Fixed with #6176
