### ISSUE TITLE
Support more than 1 condition in CASE WHEN statement

### ISSUE THREAD

**Issue by jackjlli** [apache/incubator-pinot#6243]
With this PR (https://github.com/apache/incubator-pinot/pull/5461), we now can support CASE WHEN statement, while this PR only assumes that there is only 1 condition after CASE WHEN. Queries containing more than 1 condition like below will fail:

```
SELECT CASE WHEN 'timestamp' >= 1587073457690 AND 'timestamp' < 1587077057690 THEN 1 ELSE 0 END AS columnA, SUM(someId) FROM testTable GROUP BY columnA

QueryExecutionError:\norg.apache.pinot.core.query.exception.BadQueryRequestException: Unsupported function: and with 2 parameters
at org.apache.pinot.core.operator.transform.function.TransformFunctionFactory.get(TransformFunctionFactory.java:189)
at org.apache.pinot.core.operator.transform.function.TransformFunctionFactory.get(TransformFunctionFactory.java:196)
at org.apache.pinot.core.operator.transform.TransformOperator.<init>(TransformOperator.java:56)
at org.apache.pinot.core.plan.TransformPlanNode.run(TransformPlanNode.java:52)
at org.apache.pinot.core.plan.AggregationGroupByOrderByPlanNode.run(AggregationGroupByOrderByPlanNode.java:98)
at org.apache.pinot.core.plan.AggregationGroupByOrderByPlanNode.run(AggregationGroupByOrderByPlanNode.java:41)
at org.apache.pinot.core.plan.CombinePlanNode.run(CombinePlanNode.java:94)
at org.apache.pinot.core.plan.InstanceResponsePlanNode.run(InstanceResponsePlanNode.java:33)
at org.apache.pinot.core.plan.GlobalPlanImplV0.execute(GlobalPlanImplV0.java:45)
at org.apache.pinot.core.query.executor.ServerQueryExecutorV1Impl.processQuery(ServerQueryExecutorV1Impl.java:234)
at org.apache.pinot.core.query.executor.QueryExecutor.processQuery(QueryExecutor.java:60)
at org.apache.pinot.core.query.scheduler.QueryScheduler.processQueryAndSerialize(QueryScheduler.java:155)
at org.apache.pinot.core.query.scheduler.QueryScheduler.lambda$createQueryFutureTask$0(QueryScheduler.java:139)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
```

We should fix this to accept stricter conditions.

**Comment by fx19880617** [comment]
This query can be written as:

```
SELECT
    CASE
        WHEN 'timestamp' >= 1587077057690 THEN 0
        WHEN 'timestamp' >= 1587073457690 THEN 1
        ELSE 0
    END AS columnA,
    SUM(someId)
FROM testTable
GROUP BY columnA
```

**Comment by fx19880617** [comment]
The issue here is that we tries to convert `'timestamp' >= 1587073457690 AND 'timestamp' < 1587077057690` to a transform function, which means that we need to implement `AND`/`OR`/`NOT` in transform functions and return `true`/`false` so that it will match the expression.

**Comment by fx19880617** [comment]
https://github.com/apache/incubator-pinot/pull/6249/files
