### ISSUE TITLE
Creating segment larger than 8GB will fail due to gzip limitation

### ISSUE THREAD

**Issue by dongxiaoman** [apache/incubator-pinot#6277]
We have seen failure when we try to create a segment larger than 8GB, due to limits on gzip
```
java.lang.RuntimeException: entry size '8764793433' is too big ( > 8589934591 ).
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:636) ~[et3joacc_0.commons_compress.jar:1.20]
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:624) ~[et3joacc_0.commons_compress.jar:1.20]
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:610) ~[et3joacc_0.commons_compress.jar:1.20]
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:369) ~[et3joacc_0.commons_compress.jar:1.20]
	at org.apache.pinot.common.utils.TarGzCompressionUtils.addFileToTarGz(TarGzCompressionUtils.java:78) ~[et3joapp_0.pinot_common.jar:0.6.0-2020-09-30-8a91be8a
```

Mostly fix is here: https://commons.apache.org/proper/commons-compress/javadocs/api-1.10/org/apache/commons/compress/archivers/tar/TarArchiveOutputStream.html

We need to remove the limit, but on the other hand, need to **gauge the impact of large segments**

**Comment by kkrugler** [comment]
I think this is a `tar` format limitation, not `gzip`. As per https://commons.apache.org/proper/commons-compress/tar.html, I think you want to switch to using BIGNUMBER_POSIX for the bigNumberMode so that it doesn't have an 8GB limit.

**Comment by kkrugler** [comment]
Also @kishoreg had said on Slack:

> after 2gb, we typically run into JVM limits on offset length etc.

So maybe adding a warning if the tar output size is > 2GB?

**Comment by fx19880617** [comment]
> Also @kishoreg had said on Slack:
> 
> > after 2gb, we typically run into JVM limits on offset length etc.
> 
> So maybe adding a warning if the tar output size is > 2GB?

This 2G limit is on per column size not entire segment

**Comment by pabrahamusa** [comment]
@fx19880617 Any way whether I can restrict the segment size not to go beyond 8GB , I tried setting 
"realtime.segment.flush.desired.size":"400M", but still getting the error

**Comment by fx19880617** [comment]
> @fx19880617 Any way whether I can restrict the segment size not to go beyond 8GB , I tried setting
> "realtime.segment.flush.desired.size":"400M", but still getting the error

do you have the stacktrace ?

**Comment by pabrahamusa** [comment]
@fx19880617  Here is the stack trace ,  

I tried these 
          # realtime.segment.flush.desired.size="400M" -- not sure this is working
          # "realtime.segment.flush.threshold.size": "400M" - asper docs this should work but still get below error

Only thing working for me is rows as follows, But my individual row size changes drastically so I want to fix it based on a fixed size to avoid the GZIP error

          "realtime.segment.flush.threshold.rows": "100000",
          "realtime.segment.flush.autotune.initialRows": "100000"


```
my-pinot-server-1 server 2021/02/02 19:11:26.153 ERROR [SegmentBuildTimeLeaseExtender] [pool-8-thread-1] Failed to send lease extension for mylog__0__0__20210202T1908Z
my-pinot-server-1 server 2021/02/02 19:12:40.537 ERROR [LLRealtimeSegmentDataManager_mylog__0__0__20210202T1908Z] [mylog__0__0__20210202T1908Z] Exception while in work
my-pinot-server-1 server java.lang.RuntimeException: entry size '19675344496' is too big ( > 8589934591 ).
my-pinot-server-1 server 	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:636) ~[pinot-all-0.7.0-SNAPSHOT-jar-with-dependencies.jar:0.7.0-SNAPSHOT-b4be817b1f078a4644995ad2be9ccb0eccbf6b29]
my-pinot-server-1 server 	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:624) ~[pinot-all-0.7.0-SNAPSHOT-jar-with-dependencies.jar:0.7.0-SNAPSHOT-b4be817b1f078a4644995ad2be9ccb0eccbf6b29]
my-pinot-server-1 server 	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:610) ~[pinot-all-0.7.0-SNAPSHOT-jar-with-dependencies.jar:0.7.0-SNAPSHOT-b4be817b1f078a4644995ad2be9ccb0eccbf6b29]
my-pinot-server-1 server 	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:369) ~[pinot-all-0.7.0-SNAPSHOT-jar-with-dependencies.jar:0.7.0-SNAPSHOT-b4be817b1f078a4644995ad2be9ccb0eccbf6b29]
my-pinot-server-1 server 	at org.apache.pinot.common.utils.TarGzCompressionUtils.addFileToTarGz(TarGzCompressionUtils.java:78) ~[pinot-all-0.7.0-SNAPSHOT-jar-with-dependencies.jar:0.7.0-SNAPSHOT-b4be817b1f078a4644995ad2be9ccb0eccbf6b29]
my-pinot-server-1 server 	at org.apache.pinot.common.utils.TarGzCompressionUtils.addFileToTarGz(TarGzCompressionUtils.java:91) ~[pinot-all-0.7.0-SNAPSHOT-jar-with-dependencies.jar:0.7.0-SNAPSHOT-b4be817b1f078a4644995ad2be9ccb0eccbf6b29]
```

**Comment by pabrahamusa** [comment]
So my config at the moment is this , however in the segment folder I can see massively huge segments i.e. > 4G . why this is happening. I am trying to control it to 500M .

```
          "realtime.segment.flush.threshold.rows": "100000",
          "realtime.segment.flush.autotune.initialRows": "100000",
          "realtime.segment.flush.threshold.size": "500M",
```

```
root@my-pinot-server-0:/var/pinot/server/data/index/mylog_REALTIME# du -sh *
0	consumers
520M	mylog__0__13__20210202T2001Z
4.0G	mylog__0__15__20210202T2002Z
522M	mylog__0__26__20210202T2009Z
523M	mylog__0__28__20210202T2010Z
4.5G	mylog__0__2__20210202T1952Z
518M	mylog__0__31__20210202T2012Z
746M	mylog__0__39__20210202T2017Z
492M	mylog__0__40__20210202T2017Z
521M	mylog__0__42__20210202T2018Z
4.5G	mylog__0__44__20210202T2019Z
523M	mylog__0__46__20210202T2021Z
4.6G	mylog__0__53__20210202T2024Z

```

**Comment by pabrahamusa** [comment]
@fx19880617 further analysis it is clear that the size is coming from columns.psf

```
root@my-pinot-server-0:/var/pinot/server/data/index/mylog_REALTIME/mylog__0__110__20210202T2151Z/v3# du -sh *
588K	cluster_name.lucene.index
392K	cluster_name.lucene.mapping
4.6G	columns.psf
580K	container_name.lucene.index
392K	container_name.lucene.mapping
4.0K	creation.meta
512K	host.lucene.index
392K	host.lucene.mapping
4.0K	index_map
2.7M	log.lucene.index
392K	log.lucene.mapping
8.0K	metadata.properties
540K	namespace_name.lucene.index
392K	namespace_name.lucene.mapping
640K	pod_name.lucene.index
392K	pod_name.lucene.mapping

```

**Comment by fx19880617** [comment]
Right, `column.psf` is the single file that merges all the columns' data. Do you have the index_map file or segment metadata file, which will tell the size for each column? It should give a relative ratio for the number of rows and segment size.

From the table config, you can set the flush size to a limit number, which will flush based on a hard row limit.

@npawar I think the size-based flush mechanism doesn't count index right?

**Comment by fx19880617** [comment]
Meanwhile we will fix the tar gz issue

**Comment by npawar** [comment]
The segment size threshold config will kick in only when rows threshold is set to 0. Prolly not working for you because the flush.threshold.rows is set to something in your examples.

It should be like this
```
"realtime.segment.flush.threshold.rows": "0",
  "realtime.segment.flush.threshold.time": "6h",
  "realtime.segment.flush.threshold.segment.size": "400M"
```

**Comment by fx19880617** [comment]
https://github.com/apache/incubator-pinot/pull/6533

**Comment by pabrahamusa** [comment]
@npawar , I tried the configs you provided it is not working I still get the following error

```
my-pinot-server-2 server 2021/02/03 13:21:34.725 ERROR [LLRealtimeSegmentDataManager_mylog__0__298__20210203T1319Z] [mylog__0__298__20210203T1319Z] Exception while in work
my-pinot-server-2 server java.lang.RuntimeException: entry size '12728757704' is too big ( > 8589934591 ).
my-pinot-server-2 server 	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:636) ~[pinot-all-0.7.0-SNAPSHOT-jar-with-dependencies.jar:0.7.0-SNAPSHOT-b4be817b1f078a4644995ad2be9ccb0eccbf6b29]
my-pinot-server-2 server 	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:624) ~[pinot-all-0.7.0-SNAPSHOT-jar-with-dependencies.jar:0.7.0-SNAPSHOT-b4be817b1f078a4644995ad2be9ccb0eccbf6b29]
my-pinot-server-2 server 	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:610) ~[pinot-all-0.7.0-SNAPSHOT-jar-with-dependencies.jar:0.7.0-SNAPSHOT-b4be817b1f078a4644995ad2be9ccb0eccbf6b29]
my-pinot-server-2 server 	at org.apache.commons.compress.archivers.tar.Tar

```
