### ISSUE TITLE
Spark-Pinot Connector regexp_like not worked

### ISSUE THREAD

**Issue by khanhpv** [apache/incubator-pinot#6471]
Please make a confirmation about this. We have configured spark with 
usePushDownFilters = true
but it seems spark not push down filters to pinot server, and exception thrown:

org.apache.spark.sql.AnalysisException: Undefined function: 'REGEXP_LIKE'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 44
        at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$11.$anonfun$applyOrElse$69(Analyzer.scala:1396)
        at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:53)
        at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$11.applyOrElse(Analyzer.scala:1395)
        at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$11.applyOrElse(Analyzer.scala:1386)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$1(TreeNode.scala:258)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:258)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$3(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:328)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:326)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$3(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:328)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:326)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:263)
...

**Comment by fx19880617** [comment]
I think REGEXP_LIKE is pinot specific function, which is not registered in spark SQL. So you may need to register it then use it.
cc @mangrrua

**Comment by mangrrua** [comment]
Yes, connector uses SQL instead of PQL. So it does not support regexp_like function. Use stringContains or some simirlar methods if it's fit your case.

**Comment by khanhpv** [comment]
Is there any chance to push the filters using regexp_like to pinot server instead of running filter on spark to optimize using resource? @mangrrua

**Comment by mangrrua** [comment]
I think it's not a good idea. Pinot will start using SQL instead of PQL completely. Also, connector uses SQL compiler of Pinot, and I don't know SQL compiler supports regexp_like function or not.

**Comment by fx19880617** [comment]
I feel in this case, we need to write the query in SparkSQL syntax and in the filter PushDown code (https://github.com/apache/incubator-pinot/blob/master/pinot-connectors/pinot-spark-connector/src/main/scala/org/apache/pinot/connector/spark/connector/FilterPushDown.scala#L54) to rewrite the query to Pinot `regexp_like` expression, then query Pinot.

**Comment by khanhpv** [comment]
> I feel in this case, we can still write the query in SparkSQL `LIKE` syntax. Then in the filter Push Down code (https://github.com/apache/incubator-pinot/blob/master/pinot-connectors/pinot-spark-connector/src/main/scala/org/apache/pinot/connector/spark/connector/FilterPushDown.scala#L54), the connector can rewrite the query to Pinot `regexp_like` expression, then query Pinot.

I'll try this. Thank you so much, mangrrua and fx19880617

**Comment by khanhpv** [comment]
> I think it's not a good idea. Pinot will start using SQL instead of PQL completely. Also, connector uses SQL compiler of Pinot, and I don't know SQL compiler supports regexp_like function or not.

When this release?

**Comment by fx19880617** [comment]
> > I think it's not a good idea. Pinot will start using SQL instead of PQL completely. Also, connector uses SQL compiler of Pinot, and I don't know SQL compiler supports regexp_like function or not.
> 
> When this release?

we need to make a code change for this :)

**Comment by mangrrua** [comment]
Actually, methods below uses SQL `like` method. 

```    
case StringStartsWith(attr, value) => s"$attr LIKE '$value%'" 
case StringEndsWith(attr, value) => s"$attr LIKE '%$value'"
case StringContains(attr, value) => s"$attr LIKE '%$value%'"
```

**Comment by khanhpv** [comment]
It's currently not working, everywhen I execute statements with StringContains, the Pinot server returns LIKE enum not found.

**Comment by mangrrua** [comment]
@fx19880617 Doesn't pinot sql support `like` keyword?
