### ISSUE TITLE
Unable to create offline table baseballStats while quick-start-batch launch of Apache Pinot

### ISSUE THREAD

**Issue by jnsrikanth** [apache/incubator-pinot#6813]
Hi,
I have installed Apache Pinot on Ubuntu Linux 18.0.4 as per the instructions given in the official link below.

https://docs.pinot.apache.org/basics/getting-started/running-pinot-locally

However, I am facing the below Error while starting up of Apache Pinot after issuing the below command.

bin/quick-start-batch. sh 

The Error Log from the console is below:

Executing command: StartMinion -minionHost null -minionPort 6000 -zkAddress localhost:2123
Executing command: StartServiceManager -clusterName QuickStartCluster -zkAddress localhost:2123 -port -1 -bootstrapServices []
Starting a Pinot [SERVICE_MANAGER] at 17.704s since launch
Started Pinot [SERVICE_MANAGER] instance [ServiceManager_mlops_-1] at 17.704s since launch
Starting a Pinot [MINION] at 17.704s since launch
Started Pinot [MINION] instance [Minion_10.0.0.2_6000] at 18.77s since launch
***** Bootstrap baseballStats table *****
Executing command: AddTable -tableConfigFile /tmp/1618830434961/baseballStats_1618830435084.config -schemaFile /tmp/1618830414294/baseballStats/baseballStats_schema.json -controllerProtocol http -controllerHost mlops -controllerPort 9000 -exec
{"code":400,"error":"Invalid table config for table baseballStats_OFFLINE: Failed to find instances with tag: DefaultTenant_BROKER for table: baseballStats_OFFLINE"}
Thread Thread[main,5,main] died
java.lang.RuntimeException: Unable to create offline table - baseballStats from schema file [/tmp/1618830414294/baseballStats/baseballStats_schema.json] and table conf file [/tmp/1618830414294/baseballStats/baseballStats_offline_table_config.json].
	at org.apache.pinot.tools.BootstrapTableTool.bootstrapOfflineTable(BootstrapTableTool.java:151) ~[pinot-all-0.7.1-jar-with-dependencies.jar:0.7.1-e22be7c3a39e840321d3658e7505f21768b228d6]
	at org.apache.pinot.tools.BootstrapTableTool.execute(BootstrapTableTool.java:99) ~[pinot-all-0.7.1-jar-with-dependencies.jar:0.7.1-e22be7c3a39e840321d3658e7505f21768b228d6]

Let me know what is missing in the installation or configuration procedure?

Thanks,
Srikanth

**Comment by Jackie-Jiang** [comment]
@jnsrikanth Hi Srikanth, I cannot reproduce the issue here. Which version of pinot are you running? Can you please try the latest master and see if it works?

**Comment by fx19880617** [comment]
Can you check if the broker is started as expected? Is the default broker port(8000) occupied?

**Comment by kim-kocet** [comment]
Hello,
Did you find a solution to that issue?
Thank you.
