### ISSUE TITLE
Thirdeye docker quickstart "Unrecognized field at: whitelistDatasets"

### ISSUE THREAD

**Issue by burgalon** [apache/incubator-pinot#6852]
When following the instructions of starting ThirdEye using docker I get an error:
```
docker run --network=pinot-demo \
    --name thirdeye \
    -p 1426:1426 \
    -p 1427:1427 \
    -d apachepinot/thirdeye:latest pinot-quickstart
```

```
io.dropwizard.configuration.ConfigurationParsingException: ./config/pinot-quickstart/dashboard.yml has an error:
  * Unrecognized field at: whitelistDatasets
    Did you mean?:
      - phantomJsPath
      - rootCause
      - metrics
      - cacheDataSource
      - dataSources
        [14 more]

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:140)```

**Comment by Jackie-Jiang** [comment]
@suvodeep-pyne Can you please help answer this question? Is this command still valid after moving third-eye out of pinot repo?
