### ISSUE TITLE
Support database concept to create like dbname.tablename

### ISSUE THREAD

**Issue by syed72** [apache/incubator-pinot#7072]
Hi,
 
Need support something like Mysql where we can have multiple databases and same table inside it...
i.e., dbName.TableName

{
  ****"tableName": "myDb.myTable",****
  "tableType": "OFFLINE",
  "segmentsConfig": {
    "timeColumnName": "outgoingName",
    "timeType": "DAYS",
    "retentionTimeUnit": "DAYS",
    "retentionTimeValue": "365",
    "segmentPushType": "APPEND",
    "segmentAssignmentStrategy": "BalanceNumSegmentAssignmentStrategy",
    "replication": "3"
  },
  "tenants": {
    "broker": "brokerOne",
    "server": "serverOne"
  },
  "tableIndexConfig": {
    "loadMode": "HEAP",
    "invertedIndexColumns": [
      "column1",
      "column2"
    ]
  },
  "metadata": {
    "customConfigs": {
    }
  }
}

when i tested using above config to create table config, i got below error,

**{"code":400,"error":"Table name: 'myDb.myTable_OFFLINE' containing '.' or space is not allowed"}**

Please provide support for database concept, where i can create multi database with same/different table names

@xiangfu0 

Thanks
Akram Syed

**Comment by syed72** [comment]
Can someone acknowledge this?

**Comment by Jackie-Jiang** [comment]
Pinot does not have the database concept, and requires all the table name to be unique. I believe the ask here is to allow `.` within the table name. Currently `_` is allowed as part of the table name, do you think you can replace `.` with `_` as the delimiter?

**Comment by syed72** [comment]
ProcessingException(errorCode:150, message:PQLParsingError:
org.apache.pinot.sql.parsers.SqlCompilationException: Caught exception while parsing query: select * from 59398999_Stratus_logagent_performance_review_tbl1416000000692493 limit 10
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileCalciteSqlToPinotQuery(CalciteSqlParser.java:322)
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileToPinotQuery(CalciteSqlParser.java:107)
	at org.apache.pinot.sql.parsers.CalciteSqlCompiler.compileToBrokerRequest(CalciteSqlCompiler.java:35)
	at org.apache.pinot.controller.api.resources.PinotQueryResource.getQueryResponse(PinotQueryResource.java:166)
	at org.apache.pinot.controller.api.resources.PinotQueryResource.handlePostSql(PinotQueryResource.java:137)
	at sun.reflect.GeneratedMethodAccessor274.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469))
