### ISSUE TITLE
Pinot retention failed when integrate with HDFS

### ISSUE THREAD

**Issue by cxing** [apache/incubator-pinot#7159]
**1.Realtime table can't be retention and fund exceptions in leader controller log**
2021-07-11 03:08:50.378 ERROR [ControllerPeriodicTask] [pool-12-thread-4] Caught exception while running task: RetentionManager
java.lang.IllegalArgumentException: Wrong FS: file:/user/hzpda/pinot_backup/Deleted_Segments/people_call_chat_relations, expected: hdfs://rpbt1hmn002.webex.com:8020
        at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:646) ~[hadoop-common-2.7.0.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:194) ~[hadoop-hdfs-2.7.0.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:106) ~[hadoop-hdfs-2.7.0.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305) ~[hadoop-hdfs-2.7.0.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301) ~[hadoop-hdfs-2.7.0.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.7.0.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1301) ~[hadoop-hdfs-2.7.0.jar:?]
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1424) ~[hadoop-common-2.7.0.jar:?]
        at org.apache.pinot.plugin.filesystem.HadoopPinotFS.listFiles(HadoopPinotFS.java:145) ~[pinot-hdfs-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT-${buildNumber}]
        at org.apache.pinot.controller.helix.core.SegmentDeletionManager.removeAgedDeletedSegments(SegmentDeletionManager.java:233) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-${buildNumber}]
        at org.apache.pinot.controller.helix.core.retention.RetentionManager.postprocess(RetentionManager.java:90) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-${buildNumber}]
        at org.apache.pinot.controller.helix.core.periodictask.ControllerPeriodicTask.postprocess(ControllerPeriodicTask.java:135) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-${buildNumber}]
        at org.apache.pinot.controller.helix.core.periodictask.ControllerPeriodicTask.processTables(ControllerPeriodicTask.java:101) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-${buildNumber}]
        at org.apache.pinot.controller.helix.core.periodictask.ControllerPeriodicTask.runTask(ControllerPeriodicTask.java:68) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-${buildNumber}]
        at org.apache.pinot.core.periodictask.BasePeriodicTask.run(BasePeriodicTask.java:120) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-${buildNumber}]
        at org.apache.pinot.core.periodictask.PeriodicTaskScheduler.lambda$start$0(PeriodicTaskScheduler.java:85) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-${buildNumber}]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
2021-07-11 03:08:50.379 INFO [BasePeriodicTask] [pool-12-thread-4] Finish running task: RetentionManager in 453ms

**2.Debugging from the code we found that pinot lost hdfs host and port when RetentionManager call delete old data**
<img width="1235" alt="pinot_bug" src="https://user-images.githubusercontent.com/13634486/125380271-85093380-e3c4-11eb-8e5f-01d1cd8364e1.png">

**3.SegmentDeletionManager: pinotFS.listFiles(tableNameURI, false); this function lost hdfs host and port info and next line code will return default schema file://**
<img width="1119" alt="pinot-bug-fix" src="https://user-images.githubusercontent.com/13634486/125381126-f1d0fd80-e3c5-11eb-82df-2fabd7c9dc02.png">

**Comment by xiangfu0** [comment]
I think this is already fixed by https://github.com/apache/incubator-pinot/pull/7027

Can you confirm?

**Comment by cxing** [comment]
> I think this is already fixed by #7027
> 
> Can you confirm?

Yes it's already fixed in #7027 i will close this issue, thx
