### ISSUE TITLE
ST_Contains unsupported filter

### ISSUE THREAD

**Issue by tmichaud314** [apache/incubator-pinot#7163]
Description:

The latest docs indicate support for `ST_Contains` geospatial predicate though when running a query with ST_Contains, the controller always logs this error:
```
2021/07/15 07:29:58.366 ERROR [PinotQueryResource] [grizzly-http-server-13] Caught exception while compiling SQL query: select * from "test" where ST_Contains(ST_GeomFromText("MULTIPOINT (20 20, 25 25)"),ST_GeomFromText("POINT (25 25)"))
org.apache.pinot.sql.parsers.SqlCompilationException: Unsupported filter kind: ST_CONTAINS
```
Can someone confirm that `ST_Contains` should be supported and the reported behavior is unintended?

Note - other ST functions work including ST_Area, ST_Geometry_Type, ST_GeomFromText, and ST_Distance.

Docker image tag: latest-jdk11

Complete controller stack trace:
```
2021/07/15 07:29:58.366 ERROR [PinotQueryResource] [grizzly-http-server-13] Caught exception while compiling SQL query: select * from "gains-input" where ST_Contains(ST_GeomFromText("MULTIPOINT (20 20, 25 25)"),ST_GeomFromText("POINT (25 25)"))
org.apache.pinot.sql.parsers.SqlCompilationException: Unsupported filter kind: ST_CONTAINS
	at org.apache.pinot.sql.parsers.CalciteSqlParser.updateComparisonPredicate(CalciteSqlParser.java:607) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.queryRewrite(CalciteSqlParser.java:403) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileCalciteSqlToPinotQuery(CalciteSqlParser.java:389) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileToPinotQuery(CalciteSqlParser.java:108) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.apache.pinot.sql.parsers.CalciteSqlCompiler.compileToBrokerRequest(CalciteSqlCompiler.java:35) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.apache.pinot.controller.api.resources.PinotQueryResource.getQueryResponse(PinotQueryResource.java:166) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.apache.pinot.controller.api.resources.PinotQueryResource.handlePostSql(PinotQueryResource.java:137) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at jdk.internal.reflect.GeneratedMethodAccessor116.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:353) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [pinot-all-0.8.0-SNAPSHOT-jar-with-dependencies.jar:0.8.0-SNAPSHOT-de2f0e04dca8130a09ea902787a75997b70cc16d]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Comment by Jackie-Jiang** [comment]
Can you please try `select * from "test" where ST_Contains(ST_GeomFromText("MULTIPOINT (20 20, 25 25)"),ST_GeomFromText("POINT (25 25)")) = 1` (add `= 1` for the `ST_Contains` evaluation). `ST_Contains` is modeled as a transform function instead of a filter predicate, so we need to add a comparison predicate around it

**Comment by tmichaud314** [comment]
Adding `= 1` to the query fixes the syntax error. Thank you.
