### ISSUE TITLE
Presto queries on Pinot segments failing with NPE

### ISSUE THREAD

**Issue by dharakk** [apache/incubator-pinot#7183]
Presto query on PInot segment path failing with the following error. The data table returned by the server is null. Most probably a fix in presto-pinot driver https://github.com/prestodb/presto-pinot-driver

`
java.lang.NullPointerException: null value in entry: Server_streampinot-stg22-phx3_7090=null 	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) 	at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:42) 	at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:72) 	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:124) 	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:458) 	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:437) 	at com.facebook.presto.pinot.PinotSegmentPageSource.queryPinot(PinotSegmentPageSource.java:242) 	at com.facebook.presto.pinot.PinotSegmentPageSource.fetchPinotData(PinotSegmentPageSource.java:214) 	at com.facebook.presto.pinot.PinotSegmentPageSource.getNextPage(PinotSegmentPageSource.java:161) 	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:276) 	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:241) 	at com.facebook.presto.operator.Driver.processInternal(Driver.java:418)
--
`

**Comment by dharakk** [comment]
There seems to be two reasons for this:
1) Pinot data table version might mismatch from what is expected by presto in this adding this config can fix the exception: https://github.com/apache/incubator-pinot/blob/master/kubernetes/helm/pinot/values.yaml#L301
2) The pinot query to server times out in that case the table might need some optimization. Looking more in to this on what to tune.
